### ISSUE TITLE
Ownership of "inviting new team member to GitHub org" onboarding task is unclear

### ISSUE THREAD

**Issue by michaellzc** [sourcegraph/handbook#1928]
## Context

Today is my first day and I did not receive an invite to the sourcegraph GitHub org. This is a blocker for a bunch of onboarding tasks.

In process.st, in only says `Make sure you've been added to the Sourcegraph org in GitHub` without explaining how to get an invite.

In the ENGG onboarding docs, https://handbook.sourcegraph.com/departments/product-engineering/engineering/onboarding#manager-checklist, it's People Ops responsibility to grant access.

It turns out to be Tech Ops responsibility to grant people access to the GitHub org. [learn more](https://sourcegraph.slack.com/archives/C01CSS3TC75/p1643047626133600).

## Why this should be fixed?

Go to Slack and run this query `in:#people-ops github` (or the `#it-tech-ops` channel), there are quite a few people asking for an invite to the github org.

## TODO

- [ ] Clarify ownership of the how should be sending the invite and how to ensure new hire is added to the correct team
	- Is it People Ops or Tech Ops? I found this old [thread](https://sourcegraph.slack.com/archives/CQAGQKC4A/p1616440058020500) and supposedly Ines would like to take over this task.
- [ ] Update process.st template to include instruction about what to do if I do not receive an invite.
- [ ] Update engineering docs with the same instruction above
- [ ] Automation? Maybe
		- for example https://registry.terraform.io/providers/integrations/github/latest/docs

**Comment by marybelzer** [comment]
Hi @michaellzc nice to virtually meet you and welcome to the team! Thanks for raising this, definitely sounds like something we should clarify.

For correcting the Handbook page: Once you have your Github access set up, I recommend [proposing a change](https://handbook.sourcegraph.com/handbook/editing/edit-a-single-file) to that Handbook page and adding the appropriate reviewers to verify the updated content is correct (in this case, maybe your manager or other engineering leadership). Since we all share ownership of the Handbook content, anyone can make this type of change, doesn't need to be someone in leadership. More on Handbook usage [here](https://handbook.sourcegraph.com/handbook).

For fixing process street: I recommend reaching out to @InesRoitman via the #people-ops channel in Slack who should be able to add in that information.
